title: REPPORT 
subtitle: Hawai'i's Solution for Cleaner Oceans
description: The REPPORT App empowers you to report marine debris, support Hawai'i, and contribute to cleaner oceans. Together, let's make a difference.
google_analytics:
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
gems:
  - jekyll-mentions
